name: CI

on:
  push:
    branches:
      - main1
      - feature/1
    
jobs:
  echo-message:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a message1
        run: echo "Hello, this is a CI workflow"
      - name: Echo a message2
        run: echo "This workflow runs on push to main and feature branches"
